@ECHO OFF
SETLOCAL

SET THIS_DIR=%~dp0
SET BLENDER_DIR=%PROGRAMFILES%\Blender Foundation\Blender
SET BPY_DIR=%BLENDER_DIR%\2.79\python
SET VENV_SITE_PACKAGES=%USERPROFILE%\venv_hy_blender\Lib\site-packages
SET BPY_SITE_PACKAGES=%BPY_DIR%\lib\site-packages
SET PYTHONPATH=%THIS_DIR%;%VENV_SITE_PACKAGES%;"%BPY_SITE_PACKAGES%";%PYTHONPATH%

CALL "%BLENDER_DIR%\blender.exe"
